### ISSUE TITLE
Question about Uno WiFi OTA (remote UPDI) status

### ISSUE THREAD

**Issue by jandrassy** [arduino/nina-fw#36]
In schematics of Uno WiFi I see that UPDI and reset of the 4809 are connected to ESP32. So OTA could be implemented in nina-fw acting as UPDI programmer.

Was this planed, attempted and failed for some reason or is it something postponed? 

I am thinking of making this if no one works on it or attempted it and failed for some objective reason.

**Comment by facchinm** [comment]
Hi @jandrassy ,
the plan is to use a bootloader (https://github.com/arduino/ArduinoCore-megaavr/tree/master/bootloaders and https://github.com/arduino/nina-fw/pull/32 ) because the UPDI procedure was not stable enough to be production ready.
Anyway we have an almost pure arduino porting of an UPDI programmer as [muxTO](https://github.com/arduino/ArduinoCore-megaavr/tree/master/firmwares/MuxTO) (D11 converter you can find in the Nano Every) so porting it on the nina could be a very nice community project :wink:

**Comment by sandeepmistry** [comment]
@jandrassy is your question answered? If so can we close this issue?

**Comment by jandrassy** [comment]
yes. thank you
